import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home(props) {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container'>
        <h1>
          Tienda de productos
        </h1>
        <Link href={"/products"}>Ver productos</Link>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}